[2024-05-06T10:31:07.248-0500] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-06T10:31:07.254-0500] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scenario_two_v3.second_task manual__2024-05-06T15:31:04.243697+00:00 [queued]>
[2024-05-06T10:31:07.257-0500] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scenario_two_v3.second_task manual__2024-05-06T15:31:04.243697+00:00 [queued]>
[2024-05-06T10:31:07.257-0500] {taskinstance.py:2303} INFO - Starting attempt 1 of 6
[2024-05-06T10:31:07.262-0500] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): second_task> on 2024-05-06 15:31:04.243697+00:00
[2024-05-06T10:31:07.265-0500] {standard_task_runner.py:63} INFO - Started process 28491 to run task
[2024-05-06T10:31:07.267-0500] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'scenario_two_v3', 'second_task', 'manual__2024-05-06T15:31:04.243697+00:00', '--job-id', '57', '--raw', '--subdir', 'DAGS_FOLDER/dotnet_dag.py', '--cfg-path', '/var/folders/14/31_1v10s5nvcqyswsggcn5vh0000gn/T/tmpv02lm2uz']
[2024-05-06T10:31:07.269-0500] {standard_task_runner.py:91} INFO - Job 57: Subtask second_task
[2024-05-06T10:31:07.286-0500] {task_command.py:426} INFO - Running <TaskInstance: scenario_two_v3.second_task manual__2024-05-06T15:31:04.243697+00:00 [running]> on host nestors-macbook.attlocal.net
[2024-05-06T10:31:07.311-0500] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='nestor' AIRFLOW_CTX_DAG_ID='scenario_two_v3' AIRFLOW_CTX_TASK_ID='second_task' AIRFLOW_CTX_EXECUTION_DATE='2024-05-06T15:31:04.243697+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-06T15:31:04.243697+00:00'
[2024-05-06T10:31:07.312-0500] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-06T10:31:07.318-0500] {subprocess.py:63} INFO - Tmp dir root location: /var/folders/14/31_1v10s5nvcqyswsggcn5vh0000gn/T
[2024-05-06T10:31:07.319-0500] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'dotnet run --project /Users/nestoralfaro/Desktop/pbi-scenario-two/dotnetapp/dotnetapp.csproj']
[2024-05-06T10:31:07.322-0500] {subprocess.py:86} INFO - Output:
[2024-05-06T10:31:08.113-0500] {subprocess.py:93} INFO - /Users/nestoralfaro/Desktop/pbi-scenario-two/dotnetapp/Program.cs(57,16): warning CS0219: The variable 'testQuery' is assigned but its value is never used [/Users/nestoralfaro/Desktop/pbi-scenario-two/dotnetapp/dotnetapp.csproj]
[2024-05-06T10:31:08.531-0500] {subprocess.py:93} INFO - *********************Sheet Trades:*********************
[2024-05-06T10:31:08.537-0500] {subprocess.py:93} INFO - *********************Sheet Holdings:*********************
[2024-05-06T10:31:08.550-0500] {subprocess.py:93} INFO - Running
[2024-05-06T10:31:08.550-0500] {subprocess.py:93} INFO - :
[2024-05-06T10:31:08.551-0500] {subprocess.py:93} INFO -                   CREATE TABLE IF NOT EXISTS Trades_Portfolio_BI_CaseStudy_Data
[2024-05-06T10:31:08.551-0500] {subprocess.py:93} INFO -                     (id INTEGER PRIMARY KEY AUTOINCREMENT,
[2024-05-06T10:31:08.551-0500] {subprocess.py:93} INFO -                      sheet TEXT,
[2024-05-06T10:31:08.551-0500] {subprocess.py:93} INFO -                 , "TradeDate" TEXT
[2024-05-06T10:31:08.551-0500] {subprocess.py:93} INFO - , "Trader" TEXT
[2024-05-06T10:31:08.552-0500] {subprocess.py:93} INFO - , "Security" TEXT
[2024-05-06T10:31:08.552-0500] {subprocess.py:93} INFO - , "Counterparty" TEXT
[2024-05-06T10:31:08.552-0500] {subprocess.py:93} INFO - , "Side" TEXT
[2024-05-06T10:31:08.552-0500] {subprocess.py:93} INFO - , "TradeQty" TEXT
[2024-05-06T10:31:08.552-0500] {subprocess.py:93} INFO - , "TradeCcy" TEXT
[2024-05-06T10:31:08.552-0500] {subprocess.py:93} INFO - , "UnitPrice" TEXT
[2024-05-06T10:31:08.553-0500] {subprocess.py:93} INFO - , "GrossProceeds" TEXT
[2024-05-06T10:31:08.553-0500] {subprocess.py:93} INFO - , "TotalCommission" TEXT
[2024-05-06T10:31:08.553-0500] {subprocess.py:93} INFO - , "NetProceeds" TEXT
[2024-05-06T10:31:08.553-0500] {subprocess.py:93} INFO - );
[2024-05-06T10:31:08.555-0500] {subprocess.py:93} INFO - ERROR: SQLite Error 1: 'near ",": syntax error'.
[2024-05-06T10:31:08.567-0500] {subprocess.py:97} INFO - Command exited with return code 0
[2024-05-06T10:31:08.568-0500] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-06T10:31:08.577-0500] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=scenario_two_v3, task_id=second_task, execution_date=20240506T153104, start_date=20240506T153107, end_date=20240506T153108
[2024-05-06T10:31:08.606-0500] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-06T10:31:08.613-0500] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-06T10:31:08.613-0500] {local_task_job_runner.py:222} INFO - ::endgroup::
