[2024-05-02T08:42:33.651-0500] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-02T08:42:33.658-0500] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scenario_two_v3.second_task manual__2024-05-02T13:42:30.535886+00:00 [queued]>
[2024-05-02T08:42:33.661-0500] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scenario_two_v3.second_task manual__2024-05-02T13:42:30.535886+00:00 [queued]>
[2024-05-02T08:42:33.661-0500] {taskinstance.py:2303} INFO - Starting attempt 1 of 6
[2024-05-02T08:42:33.667-0500] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): second_task> on 2024-05-02 13:42:30.535886+00:00
[2024-05-02T08:42:33.670-0500] {standard_task_runner.py:63} INFO - Started process 38953 to run task
[2024-05-02T08:42:33.672-0500] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'scenario_two_v3', 'second_task', 'manual__2024-05-02T13:42:30.535886+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/dotnet_dag.py', '--cfg-path', '/var/folders/14/31_1v10s5nvcqyswsggcn5vh0000gn/T/tmpqa9bru7s']
[2024-05-02T08:42:33.674-0500] {standard_task_runner.py:91} INFO - Job 20: Subtask second_task
[2024-05-02T08:42:33.691-0500] {task_command.py:426} INFO - Running <TaskInstance: scenario_two_v3.second_task manual__2024-05-02T13:42:30.535886+00:00 [running]> on host nestors-macbook.attlocal.net
[2024-05-02T08:42:33.718-0500] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='nestor' AIRFLOW_CTX_DAG_ID='scenario_two_v3' AIRFLOW_CTX_TASK_ID='second_task' AIRFLOW_CTX_EXECUTION_DATE='2024-05-02T13:42:30.535886+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-02T13:42:30.535886+00:00'
[2024-05-02T08:42:33.719-0500] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-02T08:42:33.727-0500] {subprocess.py:63} INFO - Tmp dir root location: /var/folders/14/31_1v10s5nvcqyswsggcn5vh0000gn/T
[2024-05-02T08:42:33.728-0500] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'echo currently in $(pwd)']
[2024-05-02T08:42:33.732-0500] {subprocess.py:86} INFO - Output:
[2024-05-02T08:42:33.735-0500] {subprocess.py:93} INFO - currently in /private/var/folders/14/31_1v10s5nvcqyswsggcn5vh0000gn/T/airflowtmpcyt81alt
[2024-05-02T08:42:33.735-0500] {subprocess.py:97} INFO - Command exited with return code 0
[2024-05-02T08:42:33.736-0500] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-02T08:42:33.747-0500] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=scenario_two_v3, task_id=second_task, execution_date=20240502T134230, start_date=20240502T134233, end_date=20240502T134233
[2024-05-02T08:42:33.777-0500] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-02T08:42:33.783-0500] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-02T08:42:33.783-0500] {local_task_job_runner.py:222} INFO - ::endgroup::
